### ISSUE TITLE
KeyError in cross_attn_forward

### ISSUE THREAD

**Issue by colorjam** [hatchetProject/QuEST#1]
Thanks for the contribution of the author.

I try to reproduce the stable diffusion quantization, but encountered the KeyError in cross_attn_forward:
![image](https://github.com/hatchetProject/QuEST/assets/23700012/42443072-1b98-4725-8d90-2d3ec3446bf0)

Command I run:
```
python txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms --cond --ptq --weight_bit 8 --quant_mode qdiff --quant_act --act_bit 8 --cali_st 25 --cali_batch_size 8 --cali_n 128 --no_grad_ckpt --split --running_stat --sm_abit 16 --cali_data_path ./sd_coco-s75_sample1024_allst.pt --outdir ./experiment --ckpt ../stable-diffusion/models/ldm/stable-diffusion-v1/sd-v1-4.ckpt
```

`sd_coco-s75_sample1024_allst.pt` is from q-diffusion repo

**Comment by hatchetProject** [comment]
Hi, thank you for pointing this out. I have updated qdiff/quant_block.py and you can use the new file now. Currently there are some leftover issues in the code that were used for debugging. We will clean them up and reorganize the code as soon as possible.

**Comment by hatchetProject** [comment]
I updated some files in the repo (please refer to them according to update time, in the main folder and the qdiff folder), you can update your code according to them.
