### ISSUE TITLE
Simulated quantization or actual quantization?

### ISSUE THREAD

**Issue by YangYang-DLUT** [hatchetProject/QuEST#15]
The current implementation of Q-diffusion is solely simulated quantization and doesn't have real benefits on speedup or memory savings. Your work outperform it, and if your method can act the actual quantization, it will be great progress. Could you offer me some information about this?

**Comment by hatchetProject** [comment]
Thanks for your interest! Our work (as well as most diffusion model quantization researches) also does simulated quantization. Actual quantization would involve much more sophisticated implementations and practical considerations. Unfortunately, we are currently not planning to move onto actual quantization. However, you can use utilize the quantization parameters to save the integer representations of weights for practical usages.

**Comment by YangYang-DLUT** [comment]
Thanks for your reply, still great work! 👍 
 About the ``Clip Score`` in experiment part, I am wondering about which tool or code repo you guys specifically used to measure it. Could you please offer me some information?

**Comment by hatchetProject** [comment]
Hi, the CLIP score is calculated based on the COCO2014 prompts. You can refer to this [link](https://huggingface.co/docs/diffusers/en/conceptual/evaluation) for the calculation process :)
