### ISSUE TITLE
Frequency of `set_timestep` in QuEST.ldm.models.diffusion.ddim.py

### ISSUE THREAD

**Issue by adilhasan927** [hatchetProject/QuEST#17]
Hello,

In ddim.py:

```python
    @torch.no_grad()
    def ddim_sampling(self, cond, shape,
...
        for i, step in enumerate(iterator):
            index = total_steps - i - 1
            ts = torch.full((b,), step, device=device, dtype=torch.long)

            # For 20 sampled timesteps
            try:
                if i % 10 == 0:
                    # print(f"Setting timestep to {step}")
                    self.model.model.diffusion_model.set_timestep(step)
                    old_step = step
                else:
                    self.model.model.diffusion_model.set_timestep(old_step)
            except:
                pass
```

So, we update the TimewiseUniformQuantizer's timestep to the current timestep on every 10th iteration.

In sample_diffusion_ldm_imagenet.py:

```python
@torch.no_grad()
def convsample_ddim(model, shape, class_label, eta=1.0):
    ddim = DDIMSampler(model)

    n_samples_per_class = shape[0]
    ddim_steps = 20
    ddim_eta = 0.0
    scale = 3.0
...
        samples_ddim, _ = ddim.sample(S=ddim_steps,
                                        conditioning=c,
                                        batch_size=n_samples_per_class,
                                        shape=[3, 64, 64],
                                        verbose=False,
                                        unconditional_guidance_scale=scale,
                                        unconditional_conditioning=uc, 
                                        eta=ddim_eta)

    return samples_ddim, _
```

Aka, the loop in `ddim_sampling()` runs for 20 iterations total, thus during inference we actually end up only updating the TimewiseUniformQuantizer timestep twice, at the 1st and 10th iterations...

However, during training we trained 20 different quantizers and updated the TimewiseUniformQuantizer timestep on every iteration, as can be seen in `pd_optimize_timeembed()` in post_layer_recon_imagenet.py...

```python
def pd_optimize_timeembed(model, cali_data, opt, logger, iters: int = 20000, timesteps: list=None, outpath: str=None,):
...
    for t in timesteps:
        model.set_timestep(t)
```

Thus, if my understanding is correct, I believe that the check for **i % 10 == 0**, should be deleted in **ddim.py**. This could improve metrics at inference time 🙂.

**Comment by hatchetProject** [comment]
Yes you are correct. The current code in ddim.py adopts the setting of LSUN-bedrooms, where it uses 200 timesteps for inference. The choice of number for the `i % n == 0` depends on the `--cali_st ` used. So it is n =200 / 20 for bedrooms, and n = 20 / 20 for ImageNet. I will clarify it in the README as well. Thanks a lot for your suggestions :) !
