### ISSUE TITLE
Quantizer implementation error?

### ISSUE THREAD

**Issue by seung-hoon-lee** [hatchetProject/QuEST#18]
Hi, thanks for sharing your awesome work.

However, It seems that there is an issue in the quantize method of ActUniformQuantizer in qdiff.quant_layer.py. Typically, asymmetric quantization involves the use of a zero-point, but it appears that the implemented code lacks the calculation process for the zero-point. 

Here is your code,
```
    def quantize(self, x, max, min):
        delta = (max - min) / (2 ** self.n_bits - 1)
        delta = torch.clamp(delta, min=1e-8)  # TODO: Added, examine effect
        zero_point = (- min / delta).round()
        # we assume weight quantization is always signed
        x_int = torch.round(x / delta)
        if self.sym:
            x_quant = torch.clamp(x_int, -self.n_levels - 1, self.n_levels)
        else:
            x_quant = torch.clamp(x_int, 0, self.n_levels - 1)
        x_float_q = (x_quant - zero_point) * delta
        return x_float_q
```

However, in qdiff.quant_layer.py line 475, there is no calculation for zero-point. I guess the correct implementation should be :
```
       else:
            x_quant = torch.clamp(x_int + zero_point, 0, self.n_levels - 1)
```

If I am misunderstanding something, please let me know.

**Comment by hatchetProject** [comment]
Thanks for pointing it out, your implementation is correct. The repo's code will be updated. 

The code for this repo was based on the LSUN-Bedroom experiments (which always use symmetric quantization), so there are some minor implementation inconsistencies that I did not notice while merging the codebases (the others directly use the similar form of quantize() function as in UniformQuantizer). Results won't be affected. Apologies for this and thanks again :)

**Comment by seung-hoon-lee** [comment]
No need to apologize. I’m glad to hear the result remains unchanged. Thank you!
