### ISSUE TITLE
Strange Results Produced on W4A4 LSUN-Bedrooms Dataset Calibration

### ISSUE THREAD

**Issue by DHKim0428** [hatchetProject/QuEST#6]
Hi,

I executed the W4A4 LSUN-Bedroom calibration using the following command:
`python sample_diffusion_ldm_bedroom.py -r models/ldm/lsun_beds256/model.ckpt -n 100 --batch_size 20 -c 200 -e 1.0  --seed 40 --ptq  --weight_bit 4 --quant_mode qdiff --cali_st 20 --cali_batch_size 32 --cali_n 256 --quant_act --act_bit 4 --a_sym --a_min_max --running_stat --cali_data_path <cali_data_path> -l <output_path>`. 

I observed that it nicely works under the W4A8 setting but produces unexpected results in the W4A4 setting. Could you please advise if there are any specific hyperparameters or configurations that need adjustment in the default code to address this problem?

Here are my results.

W4A4 Setting.
![sample_000004](https://github.com/hatchetProject/QuEST/assets/31202714/71bcf9fa-41d8-4c68-8467-3f7742fe0d57) ![sample_000002](https://github.com/hatchetProject/QuEST/assets/31202714/76835a6b-5773-4b7b-aaf9-013ca7c899ab)
W4A8 Setting.
![sample_000004](https://github.com/hatchetProject/QuEST/assets/31202714/8b61f808-42e4-4ea7-8d5f-3906f95eff01) ![sample_000002](https://github.com/hatchetProject/QuEST/assets/31202714/047d0425-f486-4b1a-962d-4ee11b99d31a)

**Comment by hatchetProject** [comment]
Hi, you can tackle this by changing the 'channel_wise argument' to True in 
aq_params = {
      'n_bits': opt.act_bit, 'symmetric': opt.a_sym, 'channel_wise': True, 
       'scale_method': a_scale_method, 'leaf_param': opt.quant_act
}.
In practice, this is actually token-wise quantization which do not influence efficiency.
Line 474 in the code deals with this issue.

**Comment by DHKim0428** [comment]
However, the experiment I did above was conducted under the 'channel_wise'=True setting... (as mentioned in line 474)

**Comment by hatchetProject** [comment]
Try excluding the --running_stat argument. I think this is probably the issue.

**Comment by DHKim0428** [comment]
Thanks a lot, I will try it.

**Comment by DHKim0428** [comment]
It works! 
![sample_000015](https://github.com/hatchetProject/QuEST/assets/31202714/4583f185-1d55-4f52-82a4-d97984f6a51d)
